### PR TITLE
accept chemical formula as input in get_material()

### PR DESCRIPTION
**Pull request by mlevant**
As in material_mu(), it is handy to get the result (the density in this case) if either the name or the formula of the material is provided in input.
If implemented, the first 13 lines of material_mu() could be replaced by:
formula, density = get_material(name)
Also material_mu_components() could be shortened.

### CODE REVIEW

**Comment by newville** [comment]
@mlevant That seems reasonable but I think it would only work for formula only for known materials, right?  The docs should clarify that,  and this probably warrants an added test.

`material_mu()` can work with any chemical formula (+ density), not just the "known materials".  So I don't think this would replace that, well unless we also made `density` and optional argument for `get_material()` which might seem kind of odd.

**Comment by mlevant** [comment]
I agree, the docs should clarify that a useful result is obtained only for known materials. Note that, if the input is not a known material, None is returned, which I guess is correct (no need for extra tests, right?).

**Comment by newville** [comment]
@mlevant Yes, updating the docstring would be a good start.  

For "adding a test", I meant to add a test to the test suite (say, around https://github.com/xraypy/XrayDB/blob/master/python/tests/test_chem_materials.py#L135) to check that passing in a formula for a known material works to get the density and that passing in a formula for an unknown material returns `None`.

**Comment by newville** [comment]
@mlevant Thanks and no worries about the tests.  I'll merge this, close #6 and add some tests.

**Pull request merged**
