### PR TITLE
Make sure vector input gives vector output regardless of length

### PR DESCRIPTION
**Pull request by kalvdans**
There are more functions with the same bug but this fixes one at least :)

### CODE REVIEW

**Comment by newville** [comment]
@kalvdans Hm, I guess it would probably be better to just remove the test for length-1 arrays:
 
```
    if len(out) == 1:
        out = out[0]
    return out
```

and just use `return out`.  I think it should probably be done consistently for all methods...

**Comment by kalvdans** [comment]
> @kalvdans Hm, I guess it would probably be better to just remove the test for length-1 arrays:
> 
> ```
>     if len(out) == 1:
>         out = out[0]
>     return out
> ```
> 
> and just use `return out`.

No, I like that scalar input gives scalar output.

**Comment by newville** [comment]
@kalvdans maybe I am not understanding what you expect.  With current master, I get

```
>>> from  xraydb import mu_elam
>>> mu_elam('Cu', 3000)
748.8544265507303
>>> mu_elam('Cu', [3000])
748.8544265507303
>>> mu_elam('Cu', [3000, 4000])
array([748.85442655, 347.34838215])
```

For sure, a 1-element array or list can be a confusing case.  What do think the outputs here should be?

I'm definitely in favor of promoting lists to numpy arrays...

**Comment by kalvdans** [comment]
> @kalvdans maybe I am not understanding what you expect. With current master, I get
> 
> ```
> >>> from  xraydb import mu_elam
> >>> mu_elam('Cu', 3000)
> 748.8544265507303
> >>> mu_elam('Cu', [3000])
> 748.8544265507303
> >>> mu_elam('Cu', [3000, 4000])
> array([748.85442655, 347.34838215])
> ```
> 
> For sure, a 1-element array or list can be a confusing case. What do think the outputs here should be?
> 
> I'm definitely in favor of promoting lists to numpy arrays...

I expect the operation to preserve the shape, like all other numpy functions. I had some generic code that sent in the K lines of elements, that suddenly failed for Lithium since it only had one K line.

**Comment by newville** [comment]
@kalvdans that sort of does not answer my question.   I don't know what makes you think this is a numpy function.

This PR is incomplete and slightly ambiguous about the description of the problem and the approach to the solution.  It's always better to be clear.   For sure, handling 1-element sequences can cause confusion.

I think you are saying the mapping should be
   scalar int, float, complex -> float
   sequence of any type and length-> ndarray of float64, perserving shape
   pandas dataframe, other complicated thing -> not sure

**Comment by kalvdans** [comment]
Oh, sorry to be unclear. I think the most natural type mapping should be:

mu_elam(string, float) -> float
mu_elam(int, float) -> float
mu_elam(string, sequence) -> sequence
mu_elam(int, sequence) -> sequence

Here I am using sequence in the [Python definition](https://docs.python.org/3/reference/datamodel.html#index-15), which should include both Python lists and numpy arrays.

**Comment by newville** [comment]
@kalvdans OK, that seems reasonable, but there are other ambiguities (shape, dtype, should list/tuples be converted back to the original data type) to consider, and the API should be consistent.  Currently, it is, even if it converts a 1-element list/tuple/array to a float which it appears you don't like.

Are you willing to try to address this in a more complete way?

**Comment by kalvdans** [comment]
You have a point there!

> Are you willing to try to address this in a more complete way?

Yes, but I don't know when I will have time. Maybe I should have opened an issue about it instead of a pull request.

**Comment by newville** [comment]
@kalvdans OK, I'll merge this and try to work on some of these related things.  Thanks!

**Comment by kalvdans** [comment]
Thanks @newville! Sorry for being slow thinking in this thread. What I wanted to say is that I don't care personally about type conversion, I'm fine with numpy array in -> Python list out, or int in -> numpy.float64 scalar out. I usually wrap code in numpy.asarray() anyway whenever I really need a sequence to be a numpy array, or list() when I really need a Python list.

That said, a specification for how the API should work is very valuable to make all functions consistent and helps when triaging whether or not an observed behaviour is a bug or a feature :)

**Pull request merged**
